#!/usr/bin/env node
/* Turns a playlist pasted out of Spotify into src/tracks.js.
 *
 *   node import.mjs [luke_music.txt]
 *
 * The paste is a flat run of lines with no delimiters of its own. What makes
 * it parseable is the duration: Spotify prints exactly one per row and never
 * prints anything else that looks like m:ss, so every duration line is the end
 * of a track and the start of the next one. Everything in between is
 *
 *     title, artist [ , artist ]* [ & artist ], album?
 *
 * where the separators arrive on their own lines because they are their own
 * elements in Spotify's markup, and the album is missing on rows that came
 * from a local file rather than the catalogue.
 *
 * Blank lines and the stray non-breaking space in each row carry no meaning,
 * so they are dropped before anything else looks at the text.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));

// m:ss, mm:ss or h:mm:ss — the hour form shows up on the long mixes.
const DURATION = /^\d+:\d{2}(?::\d{2})?$/;
const SEPARATOR = /^[,&]$/;

export function parse(text) {
  const lines = text
    .split('\n')
    .map((l) => l.replace(/\r/g, '').replace(/ /g, ' ').trim())
    .filter((l) => l !== '');

  const tracks = [];
  let block = [];

  for (const line of lines) {
    if (!DURATION.test(line)) { block.push(line); continue; }
    const track = readBlock(block, line);
    if (track) tracks.push(track);
    block = [];
  }

  // A trailing block with no duration after it means the paste was cut short.
  if (block.length) {
    throw new Error(`unterminated track at end of file: ${JSON.stringify(block)}`);
  }
  return tracks;
}

function readBlock(block, durationText) {
  if (block.length < 2) return null; // stray text, not a row

  const [title, ...rest] = block;

  // Walk the artist run: a name, then for as long as the next line is a
  // separator, another name. Whatever survives the walk is the album.
  const artists = [rest[0]];
  let i = 1;
  while (i + 1 < rest.length && SEPARATOR.test(rest[i])) {
    artists.push(rest[i + 1]);
    i += 2;
  }
  const tail = rest.slice(i);

  return {
    title,
    artists,
    album: tail.length ? tail.join(' ') : null,
    duration: durationText,
    seconds: toSeconds(durationText),
  };
}

export function toSeconds(text) {
  const parts = text.split(':').map(Number);
  return parts.reduce((total, part) => total * 60 + part, 0);
}

function main() {
  const input = resolve(process.argv[2] ?? resolve(HERE, 'luke_music.txt'));
  const tracks = parse(readFileSync(input, 'utf8'));

  const total = tracks.reduce((n, t) => n + t.seconds, 0);
  const artists = new Set(tracks.flatMap((t) => t.artists));

  // One track per line: the file is meant to be read and diffed by a person
  // when a song gets added, not just shipped.
  const body = tracks.map((t) => '  ' + JSON.stringify(t)).join(',\n');
  const out = `/* Generated by import.mjs from luke_music.txt. Do not edit by hand —
   re-run \`node import.mjs\` after pasting a fresh playlist over the .txt.

   ${tracks.length} tracks · ${artists.size} artists · ${Math.round(total / 3600)} hours */

export const TRACKS = [
${body},
];
`;

  const dest = resolve(HERE, 'src/tracks.js');
  writeFileSync(dest, out);
  console.log(`${tracks.length} tracks, ${artists.size} artists, ${fmt(total)} → ${dest}`);
}

function fmt(secs) {
  const h = Math.floor(secs / 3600);
  const m = Math.round((secs % 3600) / 60);
  return `${h}h ${m}m`;
}

// Run only when invoked directly, so the parser can be imported by a test.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
